### ISSUE TITLE
Support GitHub alerts

### ISSUE THREAD

**Issue by nzakas** [syntax-tree/mdast-util-gfm#2]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

GitHub added support for [alerts](https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/) at the end of 2023. This package doesn't currently parse this syntax.

### Solution

Update mdast-util-gfm to support alerts.

### Alternatives

Another approach would be to create a separate plugin just for alerts so anyone could mix it into their setup. However, it does seem like most people expect "GFM" to include alerts at this point.

**Comment by remcohaszing** [comment]
GitHub alerts are not a part of GFM. It’s an HTML transform. See https://github.com/rehypejs/rehype-github/issues/3 and https://github.com/remarkjs/remark-gfm/issues?q=is:issue+alert.
